# Generated by Django 2.2.6 on 2020-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=64)),
                ('business', models.CharField(default='', max_length=64)),
                ('cloud_area', models.CharField(default='', max_length=64)),
                ('os', models.CharField(default='', max_length=64)),
            ],
        ),
    ]
