# Generated by Django 2.2.6 on 2020-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=64)),
                ('path', models.CharField(default='', max_length=128)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('file_list', models.CharField(default='', max_length=128)),
                ('size', models.CharField(default='', max_length=128)),
                ('done', models.BooleanField(default=False)),
                ('creater', models.CharField(default='', max_length=128)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=64)),
                ('set', models.CharField(default='', max_length=64)),
                ('business', models.CharField(default='', max_length=64)),
                ('cloud_area', models.CharField(default='', max_length=64)),
                ('os', models.CharField(default='', max_length=64)),
                ('cpu', models.CharField(default='', max_length=64)),
                ('disk', models.CharField(default='', max_length=64)),
                ('mem', models.CharField(default='', max_length=64)),
                ('monitor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='业务名称')),
                ('job_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='任务名称')),
                ('temp_id', models.CharField(blank=True, max_length=8, null=True, verbose_name='模板ID')),
                ('temp_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='模板名称')),
                ('identifi', models.CharField(blank=True, max_length=256, null=True, verbose_name='操作识别号')),
                ('job_type', models.CharField(blank=True, max_length=32, null=True, verbose_name='模板类型')),
                ('creater', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(default='待操作', max_length=32, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='JobTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='业务名称')),
                ('temp_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='模板名称')),
                ('temp_type', models.TextField(blank=True, max_length=2048, null=True, verbose_name='模板类型')),
                ('creater', models.CharField(blank=True, max_length=32, null=True, verbose_name='创建者')),
                ('updater', models.CharField(blank=True, max_length=256, null=True, verbose_name='更新者')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('file_path', models.CharField(blank=True, max_length=256, null=True, verbose_name='文件保存路径')),
            ],
        ),
        migrations.CreateModel(
            name='JobToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField(blank=True, null=True, verbose_name='所属作业')),
                ('temp_id', models.IntegerField(blank=True, null=True, verbose_name='所属模板')),
                ('operate', models.CharField(blank=True, max_length=256, null=True, verbose_name='操作事项')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('answer_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
                ('creater', models.CharField(blank=True, max_length=256, null=True, verbose_name='责任人')),
                ('confirmer', models.CharField(blank=True, max_length=128, null=True, verbose_name='确认人')),
                ('status', models.CharField(default='未完成', max_length=16, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('type', models.CharField(default='', max_length=64)),
                ('template', models.CharField(default='', max_length=64)),
                ('symbol', models.CharField(default='', max_length=64)),
                ('business', models.CharField(default='', max_length=64)),
                ('creator', models.CharField(default='', max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(default='', max_length=64)),
                ('type', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=64)),
                ('creator', models.CharField(default='', max_length=64)),
                ('updator', models.CharField(default='', max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempToDoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time', models.DateTimeField(auto_created=True, verbose_name='完成时间')),
                ('temp_id', models.IntegerField(blank=True, null=True, verbose_name='所属模板')),
                ('operate', models.CharField(blank=True, max_length=256, null=True, verbose_name='操作事项')),
                ('note', models.CharField(blank=True, max_length=256, null=True, verbose_name='备注')),
                ('creater', models.CharField(blank=True, max_length=256, null=True, verbose_name='责任人')),
                ('confirmer', models.CharField(blank=True, max_length=128, null=True, verbose_name='确认人')),
            ],
        ),
    ]
