# Generated by Django 2.2.6 on 2020-06-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=64)),
                ('path', models.CharField(default='', max_length=128)),
                ('number', models.IntegerField(max_length=32)),
                ('file_list', models.CharField(default='', max_length=128)),
                ('size', models.IntegerField(max_length=64)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
