# Generated by Django 2.2.6 on 2020-06-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='job_instance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='job_link',
            field=models.CharField(default='', max_length=128),
        ),
    ]
