# Generated by Django 2.2.6 on 2020-06-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_auto_20200613_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostMonitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=64)),
                ('cpu', models.CharField(default='', max_length=64)),
                ('disk', models.CharField(default='', max_length=64)),
                ('mem', models.CharField(default='', max_length=64)),
                ('monitor_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
