# Generated by Django 2.2.6 on 2020-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0002_fileinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(default='', max_length=64)),
                ('type', models.CharField(default='', max_length=64)),
                ('name', models.CharField(default='', max_length=64)),
                ('creator', models.CharField(default='', max_length=64)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
