# Generated by Django 2.2.6 on 2020-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0003_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='updator',
            field=models.CharField(default='', max_length=64),
        ),
    ]
