# Generated by Django 2.2.6 on 2020-06-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0006_jobobject_jobtemplate_jobtodolist_temptodolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
