# Generated by Django 2.2.6 on 2020-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0007_auto_20200610_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='creater',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='jobtemplate',
            name='file_path',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='文件保存路径'),
        ),
    ]
