# Generated by Django 2.2.6 on 2020-06-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0008_auto_20200612_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='size',
            field=models.CharField(default='', max_length=128),
        ),
    ]
